StrikeNet/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StrikeNet.BusinessLogic.Dtos;
using StrikeNet.BusinessLogic.Services.Interface;
using StrikeNet.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace StrikeNet.Areas.Admin.Controllers
{
    public class GameController : Controller
    {
        private readonly IGameService _gameService;
        private readonly IPredictionService _predictionService;
        private readonly IIdentityService _identityService;

        public GameController(IGameService gameService, IPredictionService predictionService, IIdentityService identityService)
        {
            _gameService = gameService;
            _predictionService = predictionService;
            _identityService = identityService;
        }

        [HttpGet]
        public async Task<IActionResult> Games()
        {
            return View(await _gameService.GetGamesAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Game(int id)
        {
            var gameDto = await _gameService.GetGameAsync(id);
            return View(gameDto);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> CreateGame()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> CreateGame(GameViewModel model)
        {
            if (ModelState.IsValid)
            {
                GameDto gameDto = new GameDto();
                gameDto.Date = model.Date;
                gameDto.Id = model.Id;
                gameDto.Result = model.Result;
                gameDto.Team1 = model.Team1;
                gameDto.Team2 = model.Team2;
                var id = await _gameService.AddGameAsync(gameDto);
                return RedirectToAction(nameof(Games));
            } else
            {
                return View(model);
            }

        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> RemoveGame(int id)
        {
            if (id == 0) return NotFound();

            var gameDto = await _gameService.GetGameAsync(id);
            return View(gameDto);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> RemoveGame(GameDto gameDto)
        {
            await _gameService.RemoveGameAsync(gameDto);
            return RedirectToAction(nameof(Games));
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> UpdateGame(int id)
        {
            if (id == 0) return NotFound();

            var gameDto = await _gameService.GetGameAsync(id);

            if (gameDto != null) {
                GameViewModel model = new GameViewModel();
                model.Id = id;
                model.Team1 = gameDto.Team1;
                model.Team2 = gameDto.Team2;
                model.Date = gameDto.Date;
                model.Result = gameDto.Result;
            return View(model);
            } else
            {
                return View();
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> UpdateGame(GameViewModel model)
        {
            if (ModelState.IsValid)
            {
                GameDto gameDto = new GameDto();
                gameDto.Date = model.Date;
                gameDto.Id = model.Id;
                gameDto.Result = model.Result;
                gameDto.Team1 = model.Team1;
                gameDto.Team2 = model.Team2;
                await _gameService.UpdateGameAsync(gameDto);
                return RedirectToAction(nameof(Games));
            } else
            {
                return View(model);
            }
        }
    }
}

StrikeNet/Controllers/LeaderboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StrikeNet.BusinessLogic.Services.Interface;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace StrikeNet.Controllers
{
    [Authorize]
    public class LeaderboardController : Controller
    {
        private readonly IIdentityService _identityService;

        public LeaderboardController(IIdentityService identityService)
        {
            _identityService = identityService;
        }

        [HttpGet]
        public async Task<IActionResult> Leaderboards()
        {
            return View(await _identityService.GetLeaderboardAsync());
        }
    }
}

StrikeNet/Controllers/UitslagenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StrikeNet.BusinessLogic.Services.Interface;
using StrikeNet.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace StrikeNet.Controllers
{
    [Authorize]
    public class UitslagenController : Controller
    {
        private readonly IGameService _gameService;
        private readonly IPredictionService _predictionService;
        private readonly IIdentityService _identityService;

        public UitslagenController(IGameService gameService, IPredictionService predictionService, IIdentityService identityService)
        {
            _gameService = gameService;
            _predictionService = predictionService;
            _identityService = identityService;
        }

        [HttpGet]
        public async Task<IActionResult> Uitslagen()
        {
            return View(await _gameService.GetGamesAsync()); ;
        }

        [HttpGet]
        public async Task<IActionResult> Uitslag(int gameId)
        {
            string predictionString;
            int pointsEarned;
            bool pointsReceived;
            var game = await _gameService.GetGameAsync(gameId);
            var userClaims = HttpContext.User;
            var userName = userClaims.Identity.Name;
            var user = await _identityService.GetUserAsync(userName);
            var prediction = await _predictionService.GetPredictionAsync(gameId, user.Id);

            if (prediction == null)
            {
                predictionString = "";
                pointsEarned = 0;
                pointsReceived = true;
            }
            else
            {
                pointsEarned = await _predictionService.CompareResultsAsync(game, prediction); 
                predictionString = prediction.PredictedResult;
                pointsReceived = prediction.PointsReceived;
            }

            return View(new UitslagViewModel { Game = game, User = user, Prediction = predictionString, PointsReceived = pointsReceived, EarnedPoints = pointsEarned });
        }

        [HttpPost]
        public async Task<IActionResult> Uitslag(UitslagViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.PointsReceived == false)
                {
                    await _predictionService.AddPointsAsync(model.User.Id, model.Game.Id, model.EarnedPoints);
                    return RedirectToAction(nameof(Uitslagen));
                }
            }
            return View(model);
        }
    }
}

StrikeNet/Controllers/VoorspellingenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StrikeNet.BusinessLogic.Dtos;
using StrikeNet.BusinessLogic.Services.Interface;
using StrikeNet.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace StrikeNet.Controllers
{
    [Authorize]
    public class VoorspellingenController : Controller
    {
        private readonly IGameService _gameService;
        private readonly IPredictionService _predictionService;
        private readonly IIdentityService _identityService;

        public VoorspellingenController(IGameService gameService, IPredictionService predictionService, IIdentityService identityService)
        {
            _gameService = gameService;
            _predictionService = predictionService;
            _identityService = identityService;
        }
        
        [HttpGet]
        public async Task<IActionResult> Voorspellingen()
        {
            return View(await _gameService.GetGamesAsync()); ;
        }

        [HttpGet]
        public async Task<IActionResult> Voorspelling(int gameId, int userId)
        {
            bool hasPredicted;
            string predictionString;
            var game = await _gameService.GetGameAsync(gameId);
            var userClaims = HttpContext.User;
            var userName = userClaims.Identity.Name;
            var user = await _identityService.GetUserAsync(userName);
            var prediction = await _predictionService.GetPredictionAsync(gameId, user.Id);

            if(prediction == null)
            {
                hasPredicted = false;
                predictionString = "";
            } else
            {
                hasPredicted = true;
                predictionString = prediction.PredictedResult;
            }
            return View(new VoorspellingViewModel { Game = game, User = user, Prediction = predictionString, HasPredicted = hasPredicted });
        }

        [HttpPost]
        public async Task<IActionResult> Voorspelling(VoorspellingViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.HasPredicted == false)
                {
                    await _predictionService.SavePredictionAsync(model.Game.Id, model.User.Id, model.Prediction);
                } else
                {
                    await _predictionService.UpdatePredictionAsync(model.Game.Id, model.User.Id, model.Prediction);
                }
                return RedirectToAction(nameof(Voorspellingen));
            }

            return View(model);
        }
    }
}

StrikeNet/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
}

<h1>@ViewBag.ErrorMessage</h1>

<a asp-action="index" asp-controller="home">
    Klik hier om terug te gaan naar de homepagina.
</a>

StrikeNet/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using StrikeNet.BusinessLogic.Services.Interface;
@inject IIdentityService  _identityService;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StrikeNet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="~/css/custom.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StrikeNet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav ml-auto">
                        @if (_identityService.IsSignedIn(User))
                        {
                            var user = await _identityService.GetUserAsync(User.Identity.Name);
                            string[] names = User.Identity.Name.Split("@");

                            @if (await _identityService.IsUserInRoleAsync(user, "Admin"))
                            {
                                @*<li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Dropdown link
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" href="#">Action</a>
                                        <a class="dropdown-item" href="#">Another action</a>
                                        <a class="dropdown-item" href="#">Something else here</a>
                                    </div>*@
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="cursor:pointer">Admin<span class="caret"></span></a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Games" style="cursor:pointer">Wedstrijden</a>
                                            <a class="nav-link text-dark" asp-controller="Administration" asp-action="ListRoles" style="cursor:pointer">Rollen</a>
                                    </div>
                                </li>
                                }
                                <li class="nav-item">
                                    <form method="post" asp-action="logout" asp-controller="account">
                                        <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">Uitloggen @names[0] <br /> @user.Score punten</button>
                                    </form>
                                </li>
                                }
                                else
                                {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Registreren</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Inloggen</a>
                                </li>
                                }
                            </ul>

                    <ul class="navbar-nav">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Voorspellingen" asp-action="Voorspellingen">Voorspellingen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Uitslagen" asp-action="Uitslagen">Uitslagen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Leaderboard" asp-action="Leaderboards">Leaderboards</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - StrikeNet - <a asp-area="" asp-controller="Home" asp-action="Leaderboards">Leaderboards</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>